name: main-mirror

on:

  push:
    tags:
      - '0.*'

jobs:

  mirror:

    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      # !!! generate docs

      - name: Publish docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Publish docs
          branch: main
